## Problem 04
Find the solution to: <br>
\begin{equation}
\begin{aligned}
& \underset{X}{\text{min}}
& & f = x_1^2 + x_2^2 + x^2_3 \\
& \text{subject to}
& & h_1 = \frac{x_1^2}{4} + \frac{x_2^2}{5} + \frac{x_3^2}{25} - 1 = 0 \\
& & & h_2 = x_1 + x_2 - x_3 = 0
\end{aligned}
\end{equation}

With two contraints and three variables, there will be two state variables and one driving variable. I will make $x_1\ $ my driving variable and $x_2\ $ and $x_3\ $ my state variables

In [21]:
import numpy as np
x1_0 = 1
x2_0 = 1.561370113
x3_0 = 2.561370113
X = np.array([x2_0, x3_0, x1_0])
k = 0
eps = 10**-3
sk = np.array([X[0], X[1]])
dk = np.array([X[2]])
dfdx1 = np.array([2 * X[2]])
dfds  = np.array([2 * X[0], 2 * X[1]])
dhds  = np.array([[2 / 5 * X[0], 2 / 25 * X[1]],
                  [1, -1]])
dhdd  = np.array([[1 / 2 * X[2]], [1]])
dfdd  = dfdx1 + np.matmul(np.matmul(dfds, np.linalg.inv(dhds)), dhdd)

def minfunc(X):
    x1 = X[2]
    x2 = X[0]
    x3 = X[1]
    return x1**2 + x2**2 + x3**2

def confunc(X):
    x1 = X[2]
    x2 = X[0]
    x3 = X[1]
    h1 = x1**2 / 4 + x2**2 / 5 + x3**2 /25 - 1
    h2 = x1 + x2 -x3
    return np.array([[h1], [h2]])

def linesearch(dfdd, sk, dk, dhds_line, dhdd_line):
    alpha = 1
    b = 0.3
    t = 0.11
    counter = 0
    dhds_inv = np.linalg.inv(dhds_line)
    skstep_matrix = np.transpose(np.matmul(np.matmul(dhds_inv, dhdd_line), dfdd))
    sk1 = sk + alpha * skstep_matrix
    dk1 = dk - alpha * dfdd
    X_step = np.concatenate((sk1, dk1), axis=None)
    f = minfunc(X_step)
    phi = minfunc(np.concatenate((sk, dk), axis=None)) - alpha * t * dfdd
    while f > phi and counter<50:
        alpha = b * alpha
        sk1 = sk + alpha * skstep_matrix
        dk1 = dk - alpha * dfdd
        X_step = np.concatenate((sk1, dk1), axis=None)
        f = minfunc(X_step)
        phi = minfunc(np.concatenate((sk, dk), axis=None)) - alpha * t * dfdd
        counter += 1
    if counter == 50:
        print("linesearch failed to converge")
    return alpha, skstep_matrix

def solvefunc(driving, state_approx):
    c = 0
    x1 = driving
    x2 = state_approx[0]
    x3 = state_approx[1]
    skactual = np.array([x2, x3])
    Xpart = np.concatenate((state_approx, driving), axis=None)
    h = confunc(Xpart)
    while np.linalg.norm(h) > 10**-3 and c<30:
        sktran = np.array([[x2], [x3]]) - np.matmul(np.linalg.inv(np.array([[2 / 5 * Xpart[0], 2 / 25 * Xpart[1]], [1, -1]])), confunc(Xpart))
        x2 = sktran[0]
        x3 = sktran[1]
        skactual = np.concatenate((x2, x3), axis=None)
        Xpart = np.concatenate((x2, x3, x1), axis=None)
        h = confunc(Xpart)
        c += 1
    if c == 30:
        print("Newton Method did not Converge")
    return skactual

while dfdd**2 > eps and k < 30:
    alphak, stepmatrix= linesearch(dfdd, sk, dk, dhds, dhdd)
    dk = dk - alphak * dfdd
    sk_lin_approx = sk + alphak * stepmatrix
    sk = solvefunc(dk, sk_lin_approx)
    X = np.concatenate((sk, dk), axis=None)
    dfdx1 = np.array([2 * X[2]])
    dfds  = np.array([2 * X[0], 2 * X[1]])
    dhds  = np.array([[2 / 5 * X[0], 2 / 25 * X[1]],
                      [1, -1]])
    dhdd  = np.array([[1 / 2 * X[2]], [1]])
    dfdd  = dfdx1 + np.matmul(np.matmul(dfds, np.linalg.inv(dhds)), dhdd)
    k += 1
    print(X, dfdd)

print("x1 = " + np.array2string(X[2]) + "\nx2 = " + np.array2string(X[0]) + "\nx3 = " + np.array2string(X[1]) + "\ndfdd = " + np.array2string(dfdd))

[1.56377678 2.56094489 0.9971681 ] [3.86094135]
[1.57172479 2.55951081 0.98778602] [3.78270326]
[1.59740919 2.55455531 0.95714612] [3.52980561]
[1.67014161 2.53198298 0.86184137] [2.7748381]
[1.82798579 2.44009173 0.61210594] [0.96279792]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.8933785]
[1.95710095 2.28036751 0.32326656] [-0.89